name: build-and-push-and-pr

on:
  push:
    branches:
      - main
    paths:
      - 'appcode/**'
      - '.github/workflows/build-and-push.yml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  ECR_REPO_NAME: gitops-app
  INFRA_REPO: ${{ secrets.INFRA_REPO }}
  USE_OIDC: false

jobs:
  build-push:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Check Node version
        run: node -v

      - name: Configure AWS using OIDC
        if: env.USE_OIDC == 'true'
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_APP }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure AWS using Access Keys
        if: env.USE_OIDC != 'true'
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ls -la && ls -ltrh
          docker build -t $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPO_NAME:latest
          docker push $ECR_REGISTRY/$ECR_REPO_NAME:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPO_NAME:latest

      - name: Configure Git
        run: |
          git config --global user.email "shivam0316@gmail.com"
          git config --global user.name "shivam"

      - name: Checkout Infra Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.INFRA_REPO }}
          token: ${{ secrets.INFRA_REPO_PAT }}
          path: infra

      - name: Update terraform.tfvars image tag
        env:
          NEW_TAG: ${{ github.sha }}
        run: |
          FILE="infra/terraform/terraform.tfvars"
          echo "Updating image_tag to $NEW_TAG"

          if grep -q '^image_tag' "$FILE"; then
            sed -i "s|^image_tag *= *\".*\"|image_tag = \"$NEW_TAG\"|" "$FILE"
          else
            echo "image_tag = \"$NEW_TAG\"" >> "$FILE"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.INFRA_REPO_PAT }}
          path: infra
          commit-message: "chore: bump image_tag to ${{ github.sha }}"
          branch: bump-image-${{ github.sha }}
          title: "chore: bump image_tag to ${{ github.sha }}"
          body: |
            Auto-generated PR to update image tag to `${{ github.sha }}`.
            Image: `${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ github.sha }}`
